full_name = input("Please input your full name: ")
print(f"Full Name: {full_name}.")
print(f"First Character: {full_name[0]}.")
print(f"First Five Characters: {", ".join(full_name[0:5])}.")
print(f"Fourth, Fifth, and Sixth Characters: {", ".join(full_name[3:6])}.")
